from flask import Flask, Response, request, render_template

app = Flask(__name__)

ALLOWED_USER_AGENTS = ['curl', 'wget', 'powershell']

def is_cli_user_agent(user_agent):
    for cli_agent in ALLOWED_USER_AGENTS:
        if cli_agent in user_agent.lower():
            return True
    return False
    
def get_instructions(user_agent):
    if 'curl' in user_agent.lower():
        return "Use 'curl www.site.com/{route}' to navigate."
    elif 'powershell' in user_agent.lower():
        return "Use 'Write-Host (Invoke-WebRequest www.site.com/{route}).Content' to navigate."
    return ""    

HOME_TEMPLATE = r"""
---






██╗    ██╗███████╗██╗      ██████╗ ██████╗ ███╗   ███╗███████╗██╗
██║    ██║██╔════╝██║     ██╔════╝██╔═══██╗████╗ ████║██╔════╝██║
██║ █╗ ██║█████╗  ██║     ██║     ██║   ██║██╔████╔██║█████╗  ██║
██║███╗██║██╔══╝  ██║     ██║     ██║   ██║██║╚██╔╝██║██╔══╝  ╚═╝
╚███╔███╔╝███████╗███████╗╚██████╗╚██████╔╝██║ ╚═╝ ██║███████╗██╗
 ╚══╝╚══╝ ╚══════╝╚══════╝ ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝╚═╝


Hello! I’m Chris Bates, an IT student with a deep passion for technology and a strong drive to launch my career in cybersecurity. 
I’m currently pursuing a degree in Cybersecurity at Ozark Technical Community College, with a focus on:

- Network Security
- Vulnerability Assessment
- Penetration Testing
- Digital Forensics
- Programming

Feel free to explore the following routes to learn more about my work and background:

> /portfolio     - Explore my projects
> /resume        - View my resume
> /about         - Learn more about my background
> /contact       - Get in touch with me

Thank you for visiting!

{instructions}
"""

PORTFOLIO_CONTENT = r"""
---






██████╗  ██████╗ ██████╗ ████████╗███████╗ ██████╗ ██╗     ██╗ ██████╗ 
██╔══██╗██╔═══██╗██╔══██╗╚══██╔══╝██╔════╝██╔═══██╗██║     ██║██╔═══██╗
██████╔╝██║   ██║██████╔╝   ██║   █████╗  ██║   ██║██║     ██║██║   ██║
██╔═══╝ ██║   ██║██╔══██╗   ██║   ██╔══╝  ██║   ██║██║     ██║██║   ██║
██║     ╚██████╔╝██║  ██║   ██║   ██║     ╚██████╔╝███████╗██║╚██████╔╝
╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚═╝      ╚═════╝ ╚══════╝╚═╝ ╚═════╝ 


Explore a selection of projects I’ve developed across various categories:

===================================================================
Websites
===================================================================
> https://github.com/AlteredMinds/QrPhishingApp
   - Developed for a phishing experiment to track user interactions with QR codes.

> https://github.com/AlteredMinds/CLIWebapp
   - The site you’re currently visiting.

> http://planet-express.delivery
   - A Futurama-themed website for a cool domain.

> https://altered-eco-server.github.io/
   - A site for a game server I ran from home, dedicated to ECO.

===================================================================
Apps
===================================================================
> https://github.com/AlteredMinds/Calculator
   - A simple calculator built with .NET and C# to challenge my programming skills.

> https://github.com/AlteredMinds/EcoServerUtility
   - An application for managing my ECO game server, created with .NET and C#.

===================================================================
Scripts
===================================================================
> http://www.planet-express.delivery/hahahash.htm
   - A fun algorithm that generates a salted hash from a username and password.

> https://github.com/AlteredMinds/OTCNetConfig
   - A PowerShell script for managing network settings on school workstations.

> https://github.com/AlteredMinds/AD_UserCreator
   - A PowerShell script for creating Active Directory users with autogenerated credentials.

===================================================================
Miscellaneous
===================================================================
> https://github.com/orgs/Altered-Eco-Server/repositories
   - A repository of mods I created in C# for my ECO game server.

> https://www.github.com/AboutMyHomelab
   - Documentation for my homelab environment.
"""

RESUME_CONTENT = r"""
---






██████╗ ███████╗███████╗██╗   ██╗███╗   ███╗███████╗
██╔══██╗██╔════╝██╔════╝██║   ██║████╗ ████║██╔════╝
██████╔╝█████╗  ███████╗██║   ██║██╔████╔██║█████╗  
██╔══██╗██╔══╝  ╚════██║██║   ██║██║╚██╔╝██║██╔══╝  
██║  ██║███████╗███████║╚██████╔╝██║ ╚═╝ ██║███████╗
╚═╝  ╚═╝╚══════╝╚══════╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝


===================================================================
Christopher A. Bates
Cybersecurity Student
===================================================================

Highly motivated and detail-oriented cybersecurity student with a strong foundation in network security, digital forensics, and compliance. 
Seeking a challenging role where I can apply my technical expertise, problem-solving skills, and passion for safeguarding data confidentiality, integrity, and availability.

===================================================================
Education
===================================================================
- A.A.S. in Cybersecurity, Ozark Technical Community College (Expected 2025)
- High School Diploma, Val Verde High School (2005)

===================================================================
Skills
===================================================================
- **Network Security**            Proficient in assessing and managing network security to maintain data confidentiality, availability, and integrity.
- **Vulnerability Assessment**    Skilled in identifying security issues and single points of failure through vulnerability assessments.
- **Digital Forensics**           Experienced in discovering digital fingerprints using common forensic practices.
- **Virtualization**              Knowledgeable in deploying and managing virtual machines and networks.
- **Security Compliance**         Familiar with PCI DSS, HIPAA, GDPR, FERPA best practices, and security policy adherence.
- **Disaster Recovery**           Competent in creating backup and contingency plans to minimize impact during disasters.
- **Windows Server**              Proficient in managing DHCP, DNS, Group Policy, and Active Directory.
- **Cloud Services**              Experience in deploying and managing Azure cloud services.
- **Programming & Scripting**     Skilled in Flask, HTML, JavaScript, CSS, C#, Python, PowerShell, SQL, and Git.
- **Linux Systems**               Proficient in Linux administration and CLI operations.
- **Cisco Equipment**             Knowledgeable in configuring and troubleshooting Cisco devices.
- **Problem Solving**             Strong ability to troubleshoot and resolve technical issues effectively.

===================================================================
Certifications
===================================================================
- CompTIA Security+
- CompTIA A+
- Comptia Network+ (currently in progress)

===================================================================
Experience
===================================================================
- Shift Manager, Hardees (2017 - 2023)
  Managed restaurant operations, ensured customer satisfaction, optimized labor based on volume, and handled closing procedures.

- Problem Solver, Amazon (2023 - Present)
  Resolve order and package issues using Amazon's internal systems, applying strong troubleshooting, problem-solving, and organizational skills.

===================================================================
Contact
===================================================================
- Email: c_bates29@yahoo.com
- LinkedIn: linkedin.com/in/cbates10010111
"""

ABOUT_CONTENT = r"""
---






 █████╗ ██████╗  ██████╗ ██╗   ██╗████████╗
██╔══██╗██╔══██╗██╔═══██╗██║   ██║╚══██╔══╝
███████║██████╔╝██║   ██║██║   ██║   ██║   
██╔══██║██╔══██╗██║   ██║██║   ██║   ██║   
██║  ██║██████╔╝╚██████╔╝╚██████╔╝   ██║   
╚═╝  ╚═╝╚═════╝  ╚═════╝  ╚═════╝    ╚═╝


............................................................:::::::::;;;;;;;;;;;;
...........................................................::::::::;;:;;;;;;;;;;;
...........................................................::::::::::;;;;;;;;;;;;
................................xX$&&&&&X+X&&&$:...........:::::::::;;;;;;;;;;;;;
.............................$&$X:+;;;;++++;+$&&&&&........:::::;:;;;;;;;;;;;;;;;
.......................X$$$$&&x:..xx;;;+++;+;X+Xx&&;$&&....::::::::;;;;;;;;;;;;;;
...................$$&$&&$$&&;+x:;;X+;;++Xx+x++$x+$&&X&&&&.::::::;;;;;;;;;;;;;;;;
.................$&&$$$&&&&&;+:;;x;+$&&X$X$x+X&$X$+&&&&&&&&X::::::;;;;;;;;;;;;;;;
.................&&$$$$&&&&&x:XxXX;+$&X+$&&$x;$&&Xx$X&&&&&&&x::;:;:;;;;;;;;;;;;;;
................X&&$$&&&&&&xx&X&&&XX$XX&&X$&&$XX&&&&&&&&&&&&&::;::;;;;;;;;;;;;;;;
................$&&&&&&$X$;$;:X$XX$$....;&$&&&;xx$&&&&&&&&&&&;:;;:;;;;;;;;;;;;;;;
................XX$x+:++$;:;;;&..x:x:X;..+;::;$x$$:$;&X+x&&&&$:::;;;;;;;;;;;;;;;;
.............X$:$.x&.$X&x&;;x:..::+.$&+&&X:.::;:+&&&$X;X:;$&X&::;;;;;;;;;;;;;;;;;
...........&::x;+&x&&x.:;:$xx;:...:.:..::.::;:;;;+Xxx+$x$&+++&&&&:;;;;;;;;;;;;;;;
...........$;+:x;$&+;;&&+;&&&&&&&&&&&&&&&&&&&&&&&&$&;$:x;+++++;;:&&;;;;;;;;;;;;;;
.........X.$;.;:xx:;::X&$;+&&&&x;:::;;::::;;;+X$&&&$X;;&::Xxx:$&&&+XX;;;;;;;;;;;+
..........X;;:..x+x$$.&&&:........::::::::::;;++++xX$$&&&::$+:;:.&:;&;;;;;;;;;;;;
...........Xxx$::;;+$:.....................::::;;++xx$$$&&$+x:;:X:;+x;;;;;;;;;;+;
............;++;$&$+....::::::...............:::;+xxxXXX$$&&&&X+&;x;;;;+;+;++++++
...............&&&&x.:::::+:Xx+;.:..........:;+xxX$+X$$XXX$&&&&&&;+++;+;+;+++++++
................&&&x.:::......:.........:::::;;::;:;+X$$XX$&&&&+++++;++++++++++++
................:+X+..:......;+x+::....:+XX+:;;:..::;+XXXXX&&$X++++++++++++++++++
...............:..:::..::;X.+X+x+X....:;XX$X&X.:&Xx&X+XXXXX&XX$++++++++++++++++++
...............;..:::..:::....::;::::::;xXX$$$+;;+++xX$xxxX$Xx$++++++++++++++++++
..................X::..:::.....:.::::::;XXXXxXXx++++xXXXXXX$&Xx++++++++++++++++++
.................:x::::...........:::::+XXXxxxxXx++++xxXXXX$&X+++++++++++++++++++
.................:X::.............::.::;xXXXxxxx+++;++xXXXX$&X+++++++++++++++++++
..................X..............;:...:;+XXX$Xx+;++++xxxXXX&XX+++++++++++++++++++
..................$:..........::.......:+Xx+X$x::;;++xxXXXX&X++++++++++++++++++++
..................;:.........::...+::.:;X&;;x+:::;;+xxXXXXX&X++++++++++++++++++++
..............&&&&X:.........::.::;:::;:xxXXxxx;;;;+xxXXXX&X+++++++++++++++++++++
...........&&&&&&&&;:.......;::::+xx+x$xX&$XXXXXXx++xxXXX$&+++++++++++++x++++++++
........&&&&&&&&&&&&;::....;:+X$x$X$$&$$$$&&$&$$$XXxxxXXX&&++++++++++++++++++++++
......&&&&&&$&&&&&&&Xx;::..:xxx+xx$x&$$x$&$&&&$&$&XxxX$$$&&&x++++++++++++++++++++
....&&&&&&&&&&&&&&&&&&X+::::;+++XXX$$xx$&&&&&$$XX$XXXX&&&&&&&++++++++++++++++++++
...:&&&&&&&&&&&&&&&&&&&XX+;++++++xxXxxXXXXXXXXXXX$XX$&&&&&&&&&&++++++++++++++++++
....&&&&&&&&&&&&&&&&&&&&&$$$$x+x+xxX$&$$$$XXXXXX$&&$&&&&&&&&&&&&&xx++++++++++++++
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&XxxxxxxX&&&$XXXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&x+++++++
&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&$XXxxxX$$XXXXXX$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&$&&&&&XXX$X$$XXX$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&$X&&&$$$XXXXXXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&$X$&&&&$X$XXX$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$X$$&&&&&&&&&&&$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$X$$$$$$$$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&$$$$$&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&

Hello! I’m Chris Bates, an IT student with a love for technology and a passion for learning. Currently, I’m studying Cybersecurity at Ozark Technical Community Collage, 
where I’m learning about everything from networking to ethical hacking.

===================================================================
My Journey
===================================================================
I am currently in the second year of my studies, and my educational path has been both enriching and transformative. 
My coursework has covered a wide array of IT disciplines, including:

- **Windows Server & Active Directory**    Gaining hands-on experience with server management and directory services.
- **Cisco Networking**                     Developing a robust understanding of networking principles and configuration.
- **Virtualization & Cloud Services**      Exploring the deployment and management of virtual environments and cloud solutions.
- **Ethical Hacking & Network Security**   Learning to identify vulnerabilities and implement security measures to protect critical infrastructure.

My journey into technology began in 10th grade, when I first ventured into the world of web development using HTML and Notepad. 
What started as a simple hobby soon ignited a profound interest in Cybersecurity and Programming. Over the years, my enthusiasm has only grown, 
fueling my desire to tackle new challenges and deepen my expertise.

===================================================================
Looking Forward
===================================================================
As I continue my academic journey, I am actively seeking internships and entry-level positions to apply my knowledge and gain valuable real-world experience. 
I am eager to contribute to dynamic teams and tackle meaningful projects in the field of cybersecurity.

If you have any opportunities or would like to connect, please feel free to reach out to me via email at c_bates29@yahoo.com 
or connect with me on LinkedIn at linkedin.com/in/cbates10010111.

Thank you for visiting my page!
"""

CONTACT_CONTENT = r"""
---






 ██████╗ ██████╗ ███╗   ██╗████████╗ █████╗  ██████╗████████╗
██╔════╝██╔═══██╗████╗  ██║╚══██╔══╝██╔══██╗██╔════╝╚══██╔══╝
██║     ██║   ██║██╔██╗ ██║   ██║   ███████║██║        ██║   
██║     ██║   ██║██║╚██╗██║   ██║   ██╔══██║██║        ██║   
╚██████╗╚██████╔╝██║ ╚████║   ██║   ██║  ██║╚██████╗   ██║   
 ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝   ╚═╝   


- Email: c_bates29@yahoo.com
- LinkedIn: linkedin.com/in/cbates10010111
"""

@app.route('/')
def home():
    user_agent = request.headers.get('User-Agent')
    if not is_cli_user_agent(user_agent):
        return render_template('denied.html')
    instructions = get_instructions(user_agent)
    home_ascii_art = HOME_TEMPLATE.format(instructions=instructions)
    
    return Response(home_ascii_art, mimetype='text/plain')

@app.route('/portfolio')
def blog():
    user_agent = request.headers.get('User-Agent')
    if not is_cli_user_agent(user_agent):
        return render_template('denied.html')
    return Response(PORTFOLIO_CONTENT, mimetype='text/plain')

@app.route('/resume')
def resume():
    user_agent = request.headers.get('User-Agent')
    if not is_cli_user_agent(user_agent):
        return render_template('denied.html')
    return Response(RESUME_CONTENT, mimetype='text/plain')

@app.route('/about')
def about():
    user_agent = request.headers.get('User-Agent')
    if not is_cli_user_agent(user_agent):
        return render_template('denied.html')
    return Response(ABOUT_CONTENT, mimetype='text/plain')

@app.route('/contact')
def contact():
    user_agent = request.headers.get('User-Agent')
    if not is_cli_user_agent(user_agent):
        return render_template('denied.html')
    return Response(CONTACT_CONTENT, mimetype='text/plain')    

if __name__ == '__main__':
    app.run()	